'use client';

import { useState } from 'react';
import { KeyRound, Copy, Check } from 'lucide-react';

type PanelUser = { email: string; name: string; role: string; regions: string[] | null };

/**
 * Admin tool: issue a fresh one-time setup/recovery link for any dashboard
 * user (locked out, link expired, never activated). The link is generated by
 * the provisioning Edge Function after it independently re-verifies the
 * caller is an admin; issuing one is itself audit-logged (reset_link_issued).
 */
export function ResetLinkPanel({ users }: { users: PanelUser[] }) {
  const [email, setEmail] = useState(users[0]?.email || '');
  const [link, setLink] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const issue = async () => {
    setLoading(true);
    setError(null);
    setLink(null);
    setCopied(false);
    try {
      const res = await fetch('/api/admin/reset-link', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email }),
      });
      const body = await res.json().catch(() => ({}));
      if (!res.ok || !body?.link) {
        setError(body?.error || 'Could not issue a link.');
      } else {
        setLink(body.link);
      }
    } catch {
      setError('Could not reach the server.');
    }
    setLoading(false);
  };

  const copy = async () => {
    if (!link) return;
    try {
      await navigator.clipboard.writeText(link);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard unavailable — the link is selectable below */
    }
  };

  return (
    <div className="glass-panel p-4 sm:p-5 flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <KeyRound className="w-4 h-4 text-brand-pink-400" />
        <h2 className="text-sm font-bold text-white">Access — issue a fresh setup link</h2>
      </div>
      <p className="text-xs text-text-secondary">
        For someone locked out or whose link expired: issue a new one-time link and send it to them privately (it lets
        the holder set that account&rsquo;s password). Issuing a new link replaces any previous one.
      </p>
      <div className="flex flex-wrap items-center gap-2">
        <select
          value={email}
          onChange={(e) => {
            setEmail(e.target.value);
            setLink(null);
            setError(null);
          }}
          aria-label="Choose user"
          className="rounded-lg bg-black/30 border border-border-subtle px-3 py-2 text-sm text-white outline-none focus:border-brand-pink-500/60 min-w-[260px]"
        >
          {users.map((u) => (
            <option key={u.email} value={u.email}>
              {u.name} — {u.email} ({u.role === 'region_head' ? (u.regions || []).join(', ') : u.role})
            </option>
          ))}
        </select>
        <button
          type="button"
          onClick={issue}
          disabled={loading || !email}
          className="rounded-lg bg-brand-pink-500/20 border border-brand-pink-500/40 text-brand-pink-400 text-sm font-semibold px-4 py-2 hover:bg-brand-pink-500/30 transition-colors disabled:opacity-50"
        >
          {loading ? 'Issuing…' : 'Issue link'}
        </button>
      </div>
      {error && (
        <p role="alert" className="text-sm text-red-400 bg-red-500/10 border border-red-500/30 rounded-lg px-3 py-2">
          {error}
        </p>
      )}
      {link && (
        <div className="flex items-center gap-2">
          <input
            readOnly
            value={link}
            onFocus={(e) => e.currentTarget.select()}
            className="flex-1 rounded-lg bg-black/30 border border-emerald-500/40 px-3 py-2 text-xs text-emerald-200 outline-none"
          />
          <button
            type="button"
            onClick={copy}
            className="rounded-lg border border-border-subtle px-3 py-2 text-sm text-text-secondary hover:text-white transition-colors flex items-center gap-1.5"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>
      )}
    </div>
  );
}
